// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6nIMwsAdAkShoKjHTL6zyt7HD_Q67NZA',
    appId: '1:119121456339:web:f7e4a1b5668e8a2ee4b826',
    messagingSenderId: '119121456339',
    projectId: 'tcareer-b1f66',
    authDomain: 'tcareer-b1f66.firebaseapp.com',
    storageBucket: 'tcareer-b1f66.appspot.com',
    measurementId: 'G-EXDV4ZNC9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOtEUdszC45C8LJQFPTlyzLHHUWPORyY',
    appId: '1:119121456339:android:7c93ab3e0c1676fae4b826',
    messagingSenderId: '119121456339',
    projectId: 'tcareer-b1f66',
    storageBucket: 'tcareer-b1f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ApXV80_6nJZ2cyat1d7VYAb5d2xtm5Q',
    appId: '1:119121456339:ios:4544f4372c02ccfce4b826',
    messagingSenderId: '119121456339',
    projectId: 'tcareer-b1f66',
    storageBucket: 'tcareer-b1f66.appspot.com',
    iosClientId: '119121456339-ie933n1vactbs39a5p258amd1j3lmqnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTcareer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ApXV80_6nJZ2cyat1d7VYAb5d2xtm5Q',
    appId: '1:119121456339:ios:4544f4372c02ccfce4b826',
    messagingSenderId: '119121456339',
    projectId: 'tcareer-b1f66',
    storageBucket: 'tcareer-b1f66.appspot.com',
    iosClientId: '119121456339-ie933n1vactbs39a5p258amd1j3lmqnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTcareer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6nIMwsAdAkShoKjHTL6zyt7HD_Q67NZA',
    appId: '1:119121456339:web:2acbba5a477cfbf5e4b826',
    messagingSenderId: '119121456339',
    projectId: 'tcareer-b1f66',
    authDomain: 'tcareer-b1f66.firebaseapp.com',
    storageBucket: 'tcareer-b1f66.appspot.com',
    measurementId: 'G-114MQEDKTT',
  );
}
