// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR4DMAJE89_WIdJbyrtl40OerBc_Lhqg4',
    appId: '1:487337375301:web:ac3c75ade611de1dc2152c',
    messagingSenderId: '487337375301',
    projectId: 'tcareer-4fa50',
    authDomain: 'tcareer-4fa50.firebaseapp.com',
    storageBucket: 'tcareer-4fa50.appspot.com',
    measurementId: 'G-SYXCNES5S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB-k2Ll3-2N7eEFNRsjnd6XRTLZTSUkZs',
    appId: '1:487337375301:android:7d0d8b745397f37fc2152c',
    messagingSenderId: '487337375301',
    projectId: 'tcareer-4fa50',
    storageBucket: 'tcareer-4fa50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiPXq74-FWwO_Clp-AsmA5_n1d3w0dA_8',
    appId: '1:487337375301:ios:a0cd8674de6ca6f0c2152c',
    messagingSenderId: '487337375301',
    projectId: 'tcareer-4fa50',
    storageBucket: 'tcareer-4fa50.appspot.com',
    androidClientId: '487337375301-hub0s7fa6764p5k403air0g58i9dloei.apps.googleusercontent.com',
    iosClientId: '487337375301-cv3ekgagjq1tgj5j7gkknicbctgk09te.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTcareer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiPXq74-FWwO_Clp-AsmA5_n1d3w0dA_8',
    appId: '1:487337375301:ios:a0cd8674de6ca6f0c2152c',
    messagingSenderId: '487337375301',
    projectId: 'tcareer-4fa50',
    storageBucket: 'tcareer-4fa50.appspot.com',
    androidClientId: '487337375301-hub0s7fa6764p5k403air0g58i9dloei.apps.googleusercontent.com',
    iosClientId: '487337375301-cv3ekgagjq1tgj5j7gkknicbctgk09te.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTcareer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR4DMAJE89_WIdJbyrtl40OerBc_Lhqg4',
    appId: '1:487337375301:web:3af0175421898d93c2152c',
    messagingSenderId: '487337375301',
    projectId: 'tcareer-4fa50',
    authDomain: 'tcareer-4fa50.firebaseapp.com',
    storageBucket: 'tcareer-4fa50.appspot.com',
    measurementId: 'G-73S7CFNJF7',
  );
}
