name: Deploy Flutter web
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
      # - name: Install Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: 'stable'
      # - name: Clean build foder
      #   run: sudo rm -rf build

      # - name: Build web release
      #   run:

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD}}
          local-dir: build/web/
